version: '3.8'

services:
  postgres-test:
    image: postgres:15
    container_name: todo-test-db
    environment:
      POSTGRES_DB: todo_test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5433:5432' # Usando porta 5433 para não conflitar com outros PostgreSQL
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_test_data:
